import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const Licenses = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8 text-center">Licenses</h1>
        
        <div className="prose max-w-none space-y-8">
          <section>
            <p>
              Neura Paint uses various open-source software components, each with their own license. This page provides information about the licenses for these components and how artworks generated using our platform can be licensed.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Artwork Usage Rights</h2>
            
            <p>
              When you purchase an artwork on the Neura Paint marketplace, you receive the following license rights:
            </p>
            
            <div className="bg-muted p-6 rounded-lg">
              <h3 className="text-xl font-medium mb-4">Standard License</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Personal and commercial use</li>
                <li>Right to display the artwork</li>
                <li>Right to make physical prints for personal use</li>
                <li>Right to use the artwork in digital media (websites, social media, etc.)</li>
                <li>Cannot resell or redistribute the digital file</li>
                <li>Cannot claim copyright ownership of the original artwork</li>
              </ul>
            </div>
            
            <p className="mt-6">
              Some artwork may be available with extended licensing options, which would be specified at the time of purchase.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Content Creation Model License</h2>
            
            <p>
              The AI models used by Neura Paint for generating artwork are developed with the following licensing considerations:
            </p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>The outputs generated by our AI models are not considered derivative works of the training data</li>
              <li>Users retain the rights to the outputs they generate, subject to our Terms of Service</li>
              <li>The underlying models are proprietary technology of Neura Paint</li>
            </ul>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Open Source Dependencies</h2>
            
            <p>
              Neura Paint's platform is built using various open-source technologies, including but not limited to:
            </p>
            
            <h3 className="text-xl font-medium mt-6 mb-3">React</h3>
            <p className="text-sm text-muted-foreground">
              MIT License<br />
              Copyright (c) Meta Platforms, Inc. and affiliates.
            </p>
            
            <h3 className="text-xl font-medium mt-6 mb-3">Tailwind CSS</h3>
            <p className="text-sm text-muted-foreground">
              MIT License<br />
              Copyright (c) Tailwind Labs, Inc.
            </p>
            
            <h3 className="text-xl font-medium mt-6 mb-3">Supabase</h3>
            <p className="text-sm text-muted-foreground">
              Apache License 2.0<br />
              Copyright (c) Supabase
            </p>
            
            <h3 className="text-xl font-medium mt-6 mb-3">Lucide Icons</h3>
            <p className="text-sm text-muted-foreground">
              ISC License<br />
              Copyright (c) 2020, Lucide Contributors
            </p>
            
            <p className="mt-6">
              Complete license texts for all open-source dependencies are available in the project repository.
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-semibold mb-4">Contact</h2>
            
            <p>
              If you have any questions about licensing, please contact our legal team at:
            </p>
            <p className="mt-2">
              Email: legal@neurapaint.com
            </p>
          </section>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Licenses;
