// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raojtupslhzjikvxidll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhb2p0dXBzbGh6amlrdnhpZGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTAxMTgsImV4cCI6MjA1Nzg2NjExOH0.C8MYQyrDrv4B5wbrzdAUWv-PMr1wIJkm3Mu9Mm3qCyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create artworks bucket if it doesn't exist
(async () => {
  try {
    const { data, error } = await supabase.storage.createBucket('artworks', {
      public: true,
      fileSizeLimit: 10485760, // 10MB
    });
    
    // Check for bucket already exists error or RLS policy error
    if (error && 
      !error.message.includes('already exists') && 
      !error.message.includes('violates row-level security policy')) {
      console.error('Error creating artworks bucket:', error);
    }
  } catch (err) {
    // Just log the error, don't throw it as it would break initialization
    console.error('Error creating artworks bucket:', err);
  }
})();
